import ProductItem from "@/components/product/ProductItem";
import { Product } from "@/types/product";
import { Inter } from "next/font/google";
import Head from "next/head";
import { useEffect, useState } from "react";
import { toast } from "react-toastify";
import { getAllProducts } from "../api/product";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [products, setProducts] = useState<Product[]>([]);
  useEffect(() => {
    getAllProducts()
      .then((response) => {
        if (response.data.success) {
          setProducts(response.data.products);
        } else {
          toast.error(response.data.message);
        }
      })
      .catch((error) => {
        console.log(error);
      });
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-gray-100 w-full h-full px-24 py-14 grid grid-cols-12 gap-20">
        {products.map((product: Product) => (
          <ProductItem key={product._id} product={product} />
        ))}
      </div>
    </>
  );
}
